### ISSUE TITLE
SPARQL package?

### ISSUE THREAD

**Issue by briatte** [bearloga/WikidataQueryServiceR#1]
First, your package looks brilliant.

Second, question: I have never used the [SPARQL](https://cran.r-project.org/web/packages/SPARQL/index.html) package, but is there any reason why not to depend on it in packages like yours?

**Comment by bearloga** [comment]
First, thank you very much! :)

Second, good question! I specifically wanted to use what I think is the best package for HTTP requests ([httr](https://cran.r-project.org/package=httr)) -- and one I am most comfortable with -- but especially because I wanted my package to have an MIT license, rather than GPL-3 (which I would be forced to use if I had depended on SPARQL).

But yeah, you can totally even just use the SPARQL package instead:

```R
sparql_query <- 'PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT DISTINCT ?genre ?genreLabel WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
  ?film wdt:P31 wd:Q11424.
  ?film rdfs:label "The Cabin in the Woods"@en.
  ?film wdt:P136 ?genre.
}'

x <- SPARQL::SPARQL(url = "https://query.wikidata.org/bigdata/namespace/wdq/sparql", query = sparql_query)
x$results
```

|genre                                     |genreLabel                |
|:-----------------------------------------|:-------------------------|
|<http://www.wikidata.org/entity/Q200092>  |"horror film"@ en          |
|<http://www.wikidata.org/entity/Q471839>  |"science fiction film"@ en |
|<http://www.wikidata.org/entity/Q224700>  |"comedy horror"@ en        |
|<http://www.wikidata.org/entity/Q859369>  |"comedy-drama"@ en         |
|<http://www.wikidata.org/entity/Q1342372> |"monster film"@ en         |

compared to

```R
y <- WikidataQueryServiceR::query_wikidata(sparql_query)
y
```

|genre                                   |genreLabel           |
|:---------------------------------------|:--------------------|
|http://www.wikidata.org/entity/Q200092  |horror film          |
|http://www.wikidata.org/entity/Q471839  |science fiction film |
|http://www.wikidata.org/entity/Q224700  |comedy horror        |
|http://www.wikidata.org/entity/Q859369  |comedy-drama         |
|http://www.wikidata.org/entity/Q1342372 |monster film         |

Hope that helps!

**Comment by briatte** [comment]
That helps a lot, thanks—and it confirms that your package produces more ergonomic code, too!

Thanks again.
