### ISSUE TITLE
Notable deaths

### ISSUE THREAD

**Issue by briatte** [bearloga/WikidataQueryServiceR#2]
I would like to reproduce [this example](http://www.masalmon.eu/2017/02/12/wikideaths3_scraping/) through a SPARQL query to Wikidata, instead of relying on scraping Wikipedia like the author of the example does.

May I ask if you know how to do this? I am only starting to get a grip at using Wikidata through SPARQL.

**Comment by bearloga** [comment]
Howdy! I'd like to help (even though my SPARQL knowledge is very limited at the moment) but this question belongs more on Stack Overflow ([wikidata](http://stackoverflow.com/questions/tagged/wikidata) tag) rather than as an Issue, which is more for feature requests and bug reports.

I have an example application in the Wiki (["Being your own Netflix recommendation system (sort of)"](https://github.com/bearloga/WikidataQueryServiceR/wiki/Examples#being-your-own-netflix-recommendation-system-sort-of)) and will let you know if I write another one up that addresses this question. And there are a lot more SPARQL query examples at [this page on Wikidata](https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples).

Stack Overflow would be a good place to re-ask this question! Feel free to drop the link to it (once you've asked it) in this even after I close it.

Cheers!

**Comment by bearloga** [comment]
Oh! There's also this:

> Ratio of “famous” (≥25 sitelinks) people’s deaths since 2000. No significant increase in 2016. ([SPARQL query](https://query.wikidata.org/#%23%20Ratio%20of%20famous%20people%E2%80%99s%20deaths%20against%20all%20deaths%20since%202000.%0A%23%20A%20person%20is%20%28somewhat%20arbitrarily%29%20considered%20to%20be%20famous%20if%20they%20have%2025%20or%20more%20sitelinks.%0A%23defaultView%3ALineChart%0ASELECT%0A%28STR%28%3Fyear%29%20AS%20%3Fyear_%29%20%23%20STR%28%29%3A%20work%20around%20T150515%0A%23%20uncomment%20the%20below%20three%20lines%20for%20a%20more%20useful%20Table%20view%0A%23%28SUM%28%3Ffamous%29%20AS%20%3FfamousCount%29%0A%23%28COUNT%28person%29%20AS%20%3FtotalCount%29%0A%23%28%3FfamousCount%2F%3FtotalCount%20AS%20%3Fratio%29%0A%23%20this%20line%20compresses%20the%20above%20three%20lines%20into%20one%20because%20otherwise%20the%20Line%20Chart%20would%20display%20%3FfamousCount%20whereas%20we%20want%20%3Fratio%0A%28SUM%28%3Ffamous%29%2FCOUNT%28%3Fperson%29%20AS%20%3Fratio%29%0AWHERE%20%7B%0A%20%20%3Fperson%20wdt%3AP31%20wd%3AQ5%3B%0A%20%20%20%20%20%20%20%20%20%20wdt%3AP570%20%3Fdied%3B%0A%20%20%20%20%20%20%20%20%20%20wikibase%3Asitelinks%20%3Fsitelinks.%0A%20%20FILTER%28%3Fdied%20%3E%3D%20%222000-01-01%22%5E%5Exsd%3AdateTime%29.%0A%20%20BIND%28YEAR%28%3Fdied%29%20AS%20%3Fyear%29.%0A%20%20BIND%28IF%28%3Fsitelinks%20%3E%3D%2025%2C%201%2C%200%29%20AS%20%3Ffamous%29.%0A%7D%0AGROUP%20BY%20%3Fyear%0AORDER%20BY%20%3Fyear))
> – https://twitter.com/WikidataFacts/status/814075781957746689

**Comment by briatte** [comment]
Thanks for your answer, @bearloga – I'll move my question to SO, as suggested.
